version: "3.7"
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: ddmdemo-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - ddmdemo-network
#    command: >
#      bash -c '
#      if ! elasticsearch-plugin list | grep -q "analysis-icu"; then
#        elasticsearch-plugin install analysis-icu
#      else
#        tail -f /dev/null &
#      fi'
    restart: always

  

  minio:
    image: quay.io/minio/minio:latest
    container_name: ddmdemo-minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data
    restart: always
    networks:
      - ddmdemo-network

networks:
  ddmdemo-network:
    name: ddmdemo-network

volumes:
  minio-data: